{
 "title": "bolt-prometheus-holesky",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Transactions Preconfirmed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "bolt_sidecar_transactions_preconfirmed",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invalid Transactions Reasons",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "bolt_sidecar_validation_errors", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Remote Blocks Proposed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "bolt_sidecar_remote_blocks_proposed",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inclusion Commitments Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "bolt_sidecar_inclusion_commitments_received",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Local Blocks Proposed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "bolt_sidecar_local_blocks_proposed",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inclusion Commitments Accepted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "bolt_sidecar_inclusion_commitments_accepted",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "bolt_sidecar_http_requests_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests Durations in ms",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "bolt_sidecar_http_requests_duration_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Head Slot",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bolt_sidecar_latest_head", "legendFormat": "__auto" }
   ]
  }
 ]
}