[package]
name = "bolt-common"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true


[dependencies]
bolt-primitives.workspace = true

# external crates
tokio.workspace = true
tokio-retry.workspace = true

blst.workspace = true

alloy.workspace = true
alloy-rpc-types-engine.workspace = true

uuid.workspace = true
serde.workspace = true
serde_json.workspace = true
parking_lot.workspace = true
async-trait.workspace = true
bytes.workspace = true
hex.workspace = true


lazy_static.workspace = true
thiserror.workspace = true
eyre.workspace = true
rand.workspace = true
dotenvy.workspace = true
regex.workspace = true
jsonwebtoken.workspace = true
derive_more.workspace = true
