name: Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.21
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run Docker compose to spin up services
        run: docker compose build && docker compose up -d db

      - name: Run unit tests and generate the coverage report
        run: RUN_DB_TESTS=1 make test-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.out
          verbose: false
          flags: unittests

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.21
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@v0.4.0

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@v0.4.6

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.0

      - name: Lint
        run: make lint

      - name: Ensure go mod tidy runs without changes
        run: |
          go mod tidy
          git diff-index HEAD
          git diff-index --quiet HEAD
