use clap::Parser;
use tracing::error;

/// CLI command definitions and options.
mod cli;

/// CLI command implementations.
mod commands;

/// Shared utility functions and helpers for the CLI.
mod common;

/// Protocol Buffers definitions generated by `prost`.
mod pb;

/// Contracts and interfaces bindings for interacting with the Bolt network.
mod contracts;

#[tokio::main]
async fn main() -> eyre::Result<()> {
    let _ = dotenvy::dotenv();
    let _ = tracing_subscriber::fmt().with_target(false).try_init();

    if let Err(err) = rustls::crypto::ring::default_provider().install_default() {
        error!("Failed to install default TLS provider: {:?}", err);
    }

    cli::Opts::parse().command.run().await
}
