services:
  cb_bolt:
    image: ghcr.io/chainbound/bolt-sidecar:v0.3.0-alpha-rc.1
    container_name: cb_bolt
    environment:
      CB_MODULE_ID: BOLT
      CB_CONFIG: /cb-config.toml
      CB_SIGNER_JWT: ${CB_JWT_BOLT}
      SIGNER_SERVER: cb_signer:20000
      BOLT_SIDECAR_ENGINE_API: http://100.85.200.41:4451
      BOLT_SIDECAR_FEE_RECIPIENT: '0x0000000000000000000000000000000000000000'
      BOLT_SIDECAR_BUILDER_PROXY_PORT: '18551'
      BOLT_SIDECAR_CHAIN: holesky
      BOLT_SIDECAR_VALIDATOR_INDEXES: 1..2
      BOLT_SIDECAR_JWT_HEX: 89732cef77d7e9a20021ee8f419dbbb51bdf7f60586932c272ddef02e70cb755
      BOLT_SIDECAR_EXECUTION_API: http://100.85.200.41:4485
      BOLT_SIDECAR_CONSTRAINTS_API: http://cb_pbs:18550
      BOLT_SIDECAR_BEACON_API: http://100.85.200.41:4400
      METRICS_SERVER: 10000
      USE_FILE_LOGS: true
      RUST_LOG: debug
      MAX_LOG_FILES: 30
    volumes:
    - ./cb-bolt-config.toml:/cb-config.toml:ro
    - ./logs/BOLT:/var/logs/commit-boost
    networks:
    - signer_network
    - monitoring_network
    depends_on:
    - cb_signer
  cb_pbs:
    image: ghcr.io/chainbound/bolt-boost:v0.3.0-alpha-rc.1
    container_name: cb_pbs
    ports:
    - 18550:18550
    environment:
      CB_CONFIG: /cb-config.toml
      USE_FILE_LOGS: true
      RUST_LOG: debug
      MAX_LOG_FILES: 30
      METRICS_SERVER: 10000
    volumes:
    - ./cb-bolt-config.toml:/cb-config.toml:ro
    - ./logs/pbs:/var/logs/commit-boost
    networks:
    - monitoring_network
  cb_signer:
    image: commitboost_signer
    container_name: cb_signer
    environment:
      CB_CONFIG: /cb-config.toml
      CB_JWTS: ${CB_JWTS}
      SIGNER_SERVER: 20000
      USE_FILE_LOGS: true
      RUST_LOG: debug
      MAX_LOG_FILES: 30
      METRICS_SERVER: 10000
      CB_SIGNER_FILE: /keys.json
    volumes:
    - ./cb-bolt-config.toml:/cb-config.toml:ro
    - ././keys.json:/keys.json:ro
    - ./logs/signer:/var/logs/commit-boost
    networks:
    - signer_network
    - monitoring_network
  cb_prometheus:
    image: prom/prometheus:latest
    container_name: cb_prometheus
    ports:
    - 9090:9090
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - ./targets.json:/etc/prometheus/targets.json
    - prometheus-data:/prometheus
    networks:
    - monitoring_network
  cb_grafana:
    image: grafana/grafana:latest
    container_name: cb_grafana
    ports:
    - 3000:3000
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
    - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    - ./grafana/datasources:/etc/grafana/provisioning/datasources
    - grafana-data:/var/lib/grafana
    networks:
    - monitoring_network
    depends_on:
    - cb_prometheus
    logging:
      driver: none
volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
networks:
  monitoring_network:
    driver: bridge
  signer_network:
    driver: bridge
