export enum EventType {
  BEACON_CLIENT_URL_FOUND = "BEACON_CLIENT_URL_FOUND",
  JSONRPC_PROVIDER_URL_FOUND = "JSONRPC_PROVIDER_URL_FOUND",
  MEV_SIDECAR_URL_FOUND = "MEV_SIDECAR_URL_FOUND",
  EXPLORER_URL_FOUND = "EXPLORER_URL_FOUND",
  NEW_SLOT = "NEW_SLOT",
}
