# Ethereum Node Connections + PBS URLs

# Port to listen on for incoming JSON-RPC requests of the Commitments API. This
# port should be open on your firewall in order to receive external requests!
port = 8017
# Execution client API URL
execution_api_url = "http://localhost:8545"
# URL for the beacon client
beacon_api_url = "http://localhost:5052"
# Execution client Engine API URL. This is needed for fallback block building
# and must be a synced Geth node
engine_api_url = "http://localhost:8551"
# The port from which the Bolt sidecar will receive Builder-API requests from the Beacon client
constraints_proxy_port = 18550
# URL to forward the constraints produced by the Bolt sidecar to a server
# supporting the Constraints API, such as an MEV-Boost fork
constraints_api_url = "http://localhost:18551"
# Validator indexes of connected validators that the sidecar should accept
# commitments on behalf of. 
# Accepted values: 
#   - a comma-separated list of indexes (e.g. "1,2,3,4") 
#   - a contiguous range of indexes (e.g. "1..4") 
#   - a mix of the above (e.g. "1,2..4,6..8")
validator_indexes = "0..64"
# The JWT secret token to authenticate calls to the engine API. It can be
# either be a hex-encoded string or a file path to a file containing the
# hex-encoded secret.
engine_jwt_hex = "0x0000000000000000000000000000000000000000000000000000000000000000"
# The fee recipient address for fallback blocks
fee_recipient = "0x0000000000000000000000000000000000000000"
# Secret ECDSA key to sign commitment messages with. The public key associated
# to it must be then used when registering the operator in the `BoltManager`
# contract
commitment_private_key = "0x0000000000000000000000000000000000000000000000000000000000000000"
# Secret BLS key to sign fallback payloads with
builder_private_key = "0x0000000000000000000000000000000000000000000000000000000000000000"

# Commitments limits
[limits]
# Max number of commitments to accept per block
max_commitments_per_slot = 128
# Max committed gas per slot
max_committed_gas_per_slot = 10_000_000
# Min priority fee to accept for a commitment
min_priority_fee = 4_000_000_000 # 4 Gwei = 4 * 10^9 wei

# Chain configuration
[chain]
# Chain on which the sidecar is running
chain = "holesky"
# The slot time duration in seconds. If provided, it overrides the default for
# the selected [chain]
slot_time = 12
# The deadline in the slot at which the sidecar will stop accepting new
# commitments for the next block (parsed as milliseconds)
commitment_deadline = 8000

# Signing options. Uncomment only the signing setup you'll use:
# - single private key -> `constraints_private_key`
# - commit-boost -> `cb_signer_url`, `cb_jwt_hex`
# - keystores -> `keystore_path`, `keystore_password` or `keystore_secrets_path`
#      (depending on whether all keystores have the same passwords or not)
#
# If you plan to use delegations, uncomment the option `delegations_path` as
# well.
[constraint_signing]
# Private key to use for signing constraint messages
# constraint_private_key = "0x0000000000000000000000000000000000000000000000000000000000000000"
# cb_signer_url = "http://localhost:18551"
# cb_jwt_hex = "0x0000000000000000000000000000000000000000000000000000000000000000"
# keystore_password = "password"
# keystore_path = "./keys"
# delegations_path = "./delegations.json"

# Telemetry and Metrics
[telemetry]
metrics_port = 3300
disable_metrics = false
